services:
  redis:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
    container_name: comty-redis
    restart: unless-stopped
    ulimits:
      memlock: -1
    networks:
      - redis_network
    command: "dragonfly --logtostderr --cache_mode=true --maxmemory=8gb --cluster_mode=emulated --lock_on_hashtags --default_lua_flags=allow-undeclared-keys"

  scylla:
    image: scylladb/scylla:latest
    container_name: comty-scylla
    restart: unless-stopped
    networks:
      - scylla_network
    volumes:
      - ./data/scylladb:/var/lib/scylla
    environment:
      - SCYLLA_ARGS=--overprovisioned

  mongodb:
    image: mongo:8.0.17
    container_name: comty-mongodb
    restart: unless-stopped
    networks:
      - mongodb_network
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - ./data/mongodb:/data/db

  nats:
    image: nats:latest
    container_name: comty-nats
    restart: unless-stopped
    command: "--jetstream --store_dir /data"
    networks:
      - nats_network
    volumes:
      - ./data/nats:/data

  haproxy:
    image: haproxy:latest
    container_name: comty-haproxy
    restart: unless-stopped
    networks:
      - api_network
    ports:
      - "9000:9000"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro

  server-blue:
    container_name: comty-server-blue
    image: ragestudio/comty-server
    build:
      context: ..
      dockerfile: ./packages/server/Dockerfile
    restart: "no"
    stop_grace_period: 60s
    depends_on:
      - mongodb
      - scylla
      - redis
      - nats
    networks:
      - api_network
      - mongodb_network
      - scylla_network
      - redis_network
      - nats_network
    env_file:
      - ./.env
    volumes:
      - ./gateway.config.json:/packages/server/gateway.config.json
    environment:
      - NODE_ENV=production
      - GRACEFUL_SHUTDOWN_TIMEOUT=30
      - NATS_URL=nats://comty-nats:4222
      - AUTO_SHUTDOWN_WHEN_IDLE=true
    profiles:
      - blue

  server-green:
    container_name: comty-server-green
    image: ragestudio/comty-server
    build:
      context: ..
      dockerfile: ./packages/server/Dockerfile
    restart: "no"
    stop_grace_period: 60s
    depends_on:
      - mongodb
      - scylla
      - redis
      - nats
    networks:
      - api_network
      - mongodb_network
      - scylla_network
      - redis_network
      - nats_network
    env_file:
      - ./.env
    volumes:
      - ./gateway.config.json:/packages/server/gateway.config.json
    environment:
      - NODE_ENV=production
      - GRACEFUL_SHUTDOWN_TIMEOUT=30
      - NATS_URL=nats://comty-nats:4222
      - AUTO_SHUTDOWN_WHEN_IDLE=true
    profiles:
      - green

  sfu-node:
    container_name: comty-sfu-node
    image: ragestudio/comty-sfu-node
    build:
      context: ..
      dockerfile: ./packages/sfu-node/Dockerfile
    restart: "unless-stopped"
    environment:
      - NATS_ADDRESS=nats:4222
    ports:
      - "40001:40001/tcp"
      - "40001:40001/udp"
    depends_on:
      - nats
    networks:
      - nats_network
      - api_network
      - redis_network

networks:
  api_network:
  mongodb_network:
  scylla_network:
  redis_network:
  nats_network:
