module.exports = {
    SESSION_INVALID: "DISRUPT",
    OVERLAY_BADPOSITION: "IGNORE",
    INTERNAL_PROCESS_FAILED: "CRITICAL",
    INVALID_DATA: "DISRUPT",
    INVALID_PROPS: "IGNORE",
    MISSING_REQUIRED_PAYLOAD: "IGNORE"
}
  