module.exports = {
    400: "SESSION_INVALID",
    210: "OVERLAY_BADPOSITION",
    110: "INTERNAL_PROCESS_FAILED",
    120: "INVALID_DATA",
    130: "INVALID_PROPS",
    140: "MISSING_REQUIRED_PAYLOAD"
}
  