module.exports = {
    403: "SESSION_INVALID",
    210: "OVERLAY_BADPOSITION",
    110: "INTERNAL_PROCESS_FAILED",
    120: "INVALID_DATA",
    130: "INVALID_PROPS",
    140: "INVALID_INDEX",
    150: "MISSING_REQUIRED_PAYLOAD"
}
  