module.exports = {
    siteName: 'Comty',
    copyright: 'RageStudio©',

    LogoPath: '/logo.svg',
    FullLogoPath: '/full_logo.svg',
    DarkFullLogoPath: '/dark_full_logo.svg',
    DarkLogoPath: '/dark_logo.svg',

    apiPrefix: '/api/v1',
    fixedHeader: true, // sticky primary layout header
    resource_bundle: 'light_ng',

    App_Config: {
      InitRes: { width: 1000, height: 900},
      InitOpenConsole: true,
    },
  
    /* Layout configuration, specify which layout to use for route. */
    layouts: [
      {
        name: 'primary',
        include: [/.*/],
        exclude: [/\/login/, /\/socket\/(.*)/, /\/publics/, /\/authorize/],
      },
    ],
    yConfig: {
      //  Disused Variables, exported from yCoreWorker
      // Global Server Key (Requiered for RS-YIBTP), Not autogenerated, must be included on. (Recommended not modify this constants)
      server_key: "f706b0a535b6c2d36545c4137a0a3a26853ea8b5-1223c9ba7923152cae28e5a2e7501b2b-50600768",
      openwheater_apiKey:'2acf34be0b8f033b89ba4de1e674d42a',
    },
    
    
    /* I18n configuration, `languages` and `defaultLanguage` are required currently. */
    i18n: {
      /* Countrys flags: https://www.flaticon.com/packs/countrys-flags */
      languages: [    
        {
          key: 'en',
          title: 'English',
        },
      ],
      defaultLanguage: 'en',
    },
  }


