services:
    api:
        build: .
        restart: unless-stopped
        networks:
            - internal_network
        ports:
            - "9000:9000"
        env_file:
            - ./.env

    redis:
        image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
        restart: unless-stopped
        ulimits:
            memlock: -1
        networks:
            - internal_network
        command: "dragonfly --logtostderr --cache_mode=true --maxmemory=8gb --cluster_mode=emulated --lock_on_hashtags --default_lua_flags=allow-undeclared-keys"

networks:
    internal_network:
