version: "3"

services:
  db:
    image: "mongo:5.0"
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - "./d_data/db:/data/db"
  api: 
    build: "."
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "3001:3001"